services:
  - type: web
    name: houkago-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WEB_CONCURRENCY
        value: 1
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 300 --workers 1 --threads 2"
